{% set name = "strawberry-graphql-django" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8e4da26d0b6eff1d3c4e19e1e7d7e634ebdad907f1ca116c4295c3cae20181d9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - poetry >=0.12
  run:
    - django >=3.0
    - python >=3.7
    - strawberry-graphql >=0.109.0

test:
  imports:
    - strawberry_django
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/strawberry-graphql/strawberry-graphql-django
  summary: Strawberry GraphQL Django extension
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
