{% set name = "strawberry-graphql-django" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/strawberry-graphql-django-{{ version }}.tar.gz
  sha256: d66dd816211b5e4a60920a9e0697c1df63d8e14edf02ab04e1c1b696d19eda33

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - poetry >=0.12
  run:
    - django >=3.0
    - python >=3.7
    - strawberry-graphql >=0.109.0

test:
  imports:
    - strawberry_django
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/strawberry-graphql/strawberry-graphql-django
  summary: Strawberry GraphQL Django extension
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
