{% set name = "strawberry-graphql-django" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 148c5aa99ecf67f826e87205dd26be4f9cd34fc0e221fb9c811656d2bf69d441

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - poetry >=0.12
  run:
    - django >=3.0
    - python >=3.7
    - strawberry-graphql >=0.109.0

test:
  imports:
    - strawberry_django
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/strawberry-graphql/strawberry-graphql-django
  summary: Strawberry GraphQL Django extension
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
